secrets:
  SECRETKEY:
    file: ./secrets/SECRETKEY
  scheduler_AUTH:
    file: ./secrets/scheduler_AUTH
  setup_TOKEN:
    file: ./secrets/setup_TOKEN
  memory_AUTH_TOKEN:
    file: ./secrets/memory_AUTH_TOKEN
  database_PASSWORD:
    file: ./secrets/database_PASSWORD
  alert_URL:
    file: ./secrets/alert_URL
  admin_alert_URL:
    file: ./secrets/admin_alert_URL

services:
  chimera:
    secrets:
      - SECRETKEY
      - scheduler_AUTH
      - setup_TOKEN
      - memory_AUTH_TOKEN
      - database_PASSWORD
      - alert_URL
      - admin_alert_URL
    environment:
      SECRETKEY_FILE: /run/secrets/SECRETKEY
      scheduler_AUTH_FILE: /run/secrets/scheduler_AUTH
      setup_TOKEN_FILE: /run/secrets/setup_TOKEN
      memory_AUTH_TOKEN_FILE: /run/secrets/memory_AUTH_TOKEN
      database_PASSWORD_FILE: /run/secrets/database_PASSWORD
      alert_URL_FILE: /run/secrets/alert_URL
      admin_alert_URL_FILE: /run/secrets/admin_alert_URL

  certbot:
    secrets:
      - alert_URL

  postgres:
    secrets:
      - database_PASSWORD
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database_PASSWORD
