require("dotenv").config()
module.exports = {
	webhookAlert: require("./utils/webhookAlert.js"),
	alertTime: require("./utils/alertTime.js"),
	auth: require("./utils/auth.js"),
	timingSafeCompare: require("./utils/timingSafeCompare.js"),
	tracker: require("./utils/tracker.js"),
	handleServerStart: require("./utils/handleServerStart.js"),
	handleSecureServerStart: require("./utils/handleSecureServerStart.js"),
	watchCertRenewal: require("./utils/watchCertRenewal.js"),
	validateBody: require("./utils/validateBody.js"),
	password: require("./utils/password.json"),
	subprocess: require("./utils/subprocess.js"),
	formatBytes: require("./utils/formatBytes.js"),
	mapLimit: require("./utils/mapLimit.js"),
	tempMiddleware: require("./utils/tempMiddleware.js"),
	jsonFileHanding: require("./utils/jsonFileHandling.js"),
	randomID: require("./utils/randomID.js"),
	helmetOptions: require("./utils/helmetOptions.js"),
	loadCameras: require("./utils/loadCameras.js").loadCameras,
	cameraConfDir: require("./utils/loadCameras.js").cameraConfDir,
	cameraConfFiles: require("./utils/loadCameras.js").cameraConfFiles,
	pruneInterval: require("./utils/pruneInterval.js"),
	createPool: require("./utils/createPool.js"),
	withTransaction: require("./utils/withTransaction.js"),
	schedulableUrls: require("./utils/schedulableUrls.js"),
	gatewayHost: require("./utils/gatewayHost.js"),
	storageHost: require("./utils/storageHost.js"),
	isPrimeInstance: !("NODE_APP_INSTANCE" in process.env) || process.env.NODE_APP_INSTANCE === "0"
}