name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4.0.3
        with:
          node-version: 22

      - name: Generate test .env
        run: cp .github/ci.env .env

      - name: Install root dependencies
        run: npm ci

      - name: Install module dependencies
        run: npm run install:modules

      - name: Run tests
        run: npm test

      - name: Coverage report comment
        if: ${{ always() && github.event_name == 'pull_request' }}
        continue-on-error: true
        uses: MishaKav/jest-coverage-comment@25f2818fee93043532f640ad32a7565b4bd4ea9a # v1.0.34
        with:
          coverage-summary-path: ./coverage/coverage-summary.json

      - name: Upload coverage artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v4.3.1
        with:
          name: coverage
          path: coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4.0.3
        with:
          node-version: 22

      - name: Install root dependencies
        run: npm ci

      - name: Install module dependencies
        run: npm run install:modules:frontend

      - name: Build frontend
        run: npm run build:command

      - name: Upload build artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v4.3.1
        with:
          name: command-dist
          path: command/dist

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4.0.3
        with:
          node-version: 22

      - name: Install root dependencies
        run: npm ci

      - name: Install module dependencies
        run: npm run install:modules:frontend

      - name: Install Playwright browser
        run: npm run e2e:install

      - name: Run e2e tests
        run: npm run e2e:command

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v4.3.1
        with:
          name: playwright-report
          path: command/playwright-report
